module.exports = {
    $schema: 'https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json',
    version: '0.2',
    ignorePaths: ['node_modules', '**/*.svg'],
    import: '@cspell/dict-ru_ru/cspell-ext.json',
    useGitignore: true,
    language: 'en,ru',
    words: [
        // Made up
        'progressable',
        'hideable',
        'pinnable',
        'datetime',
        'dont',
        'consts',
        'sidenav',
        'timespan',
        'typedefs',
        // FS
        'huskyrc',
        'npmrc',
        'vhosts',
        // Libraries
        'packagr',
        'ngneat',
        'Keycloak',
        'Menlo',
        'matero',
        'devkit',
        'loglevel',
        'photoviewer',
        'fesm',
        'ngcc',
        'inputmask',
        'codegen',
        'titlecase',
        'dinero',
        // Local names
        'Wachter',
        'Deanonimus',
        'vality',
        'valitydev',
        'Magista',
        'Machinegun',
        // Local terms
        'ruleset',
        'rulesets',
        'proto',
        'authorisation', //GB
        'preauthorization',
        'submain',
        // Terms
        'IBAN',
        'chargeback',
        'chargebacks',
    ],
};
