name: Init
description: Init
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
      shell: bash
