name: 'PR'

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: $(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-frontend/setup@v0.1
      - run: npm ci
      - name: Check
        run: npm run check
      - name: Build
        run: npm run build
      - name: Publish Angular Core
        working-directory: ./projects/ng-core/dist
        run: npm version prerelease --preid pr-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish ESLint Config
        working-directory: ./projects/eslint-config
        run: npm version prerelease --preid pr-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish CSpell Config
        working-directory: ./projects/cspell-config
        run: npm version prerelease --preid pr-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Prettier Config
        working-directory: ./projects/prettier-config
        run: npm version prerelease --preid pr-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
