name: 'PR'

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: valitydev/action-frontend/setup@v0.1
      - run: npm ci
      - name: Format
        run: npm run format:check
      - name: Build
        run: npm run build
      - name: Version up
        working-directory: ./dist/ng-core
        run: npm version prerelease --preid pr-${{github.event.number}}-${GITHUB_SHA::7} --no-git-tag-version --tag pr
      - name: Publish
        working-directory: ./dist/ng-core
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
