name: 'PR'

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: $(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-frontend/setup@v1.0
      - run: npm ci
      - name: Check
        run: npm run check
      - name: Build
        run: npm run build
      - name: Publish Angular Core
        if: contains(github.event.issue.labels.*.name, 'rc')
        working-directory: ./projects/ng-core/dist
        run: npm version prerelease --preid rc-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish ESLint Config
        if: contains(github.event.issue.labels.*.name, 'RC')
        working-directory: ./projects/eslint-config
        run: npm version prerelease --preid rc-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish CSpell Config
        if: contains(github.event.issue.labels.*.name, 'RC')
        working-directory: ./projects/cspell-config
        run: npm version prerelease --preid rc-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Prettier Config
        if: contains(github.event.issue.labels.*.name, 'RC')
        working-directory: ./projects/prettier-config
        run: npm version prerelease --preid rc-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version && npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
